#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0-or-later
"""Build the version-pinned ARM7 patch and generate a shared C header."""
from pathlib import Path
import os, struct, subprocess
root = Path(__file__).resolve().parents[1]
prefix = Path(os.environ.get('WONDERFUL_TOOLCHAIN','/opt/wonderful'))/'toolchain/gcc-arm-none-eabi/bin/arm-none-eabi-'
out = root/'build/twl-patch'; out.mkdir(parents=True,exist_ok=True)
elf = out/'twl_input.elf'
subprocess.run([str(prefix)+'gcc','-Os','-std=c11','-Wall','-Wextra','-Werror',
    '-mcpu=arm7tdmi','-marm','-ffreestanding','-fno-builtin','-fno-strict-aliasing',
    '-nostdlib','-Wl,--no-warn-rwx-segments','-T'+str(root/'patches/twl_input.ld'),
    str(root/'patches/twl_input.c'),'-o',str(elf)],check=True)
symbols = subprocess.check_output([str(prefix)+'nm',str(elf)],text=True)
address = {l.split()[-1]:int(l.split()[0],16) for l in symbols.splitlines() if len(l.split())==3}
header = '/* Generated by patches/build.py; SPDX-License-Identifier: GPL-3.0-or-later */\n'
for section in ['main','task']:
    binary = out/(section+'.bin')
    subprocess.run([str(prefix)+'objcopy','-O','binary','--only-section=.'+section,str(elf),str(binary)],check=True)
    data = binary.read_bytes()
    header += f'static const uint32_t twl_{section}[] = {{\n'
    for i in range(0,len(data),16):
        header += '    '+', '.join(f'0x{x:08X}' for x in struct.unpack('<'+'I'*(len(data[i:i+16])//4),data[i:i+16]))+',\n'
    header += '};\n'
    print(section,len(data),'bytes')
header += f'#define TWL_MODE_BRANCH 0x{(0xea000000 | (((address["twlModeReady"]-0x0380919c-8)//4)&0xffffff)):08X}u\n'
target=root/'include/twl_input_generated.h'
if not target.exists() or target.read_text()!=header: target.write_text(header)
