; These relative paths expect the nds binaries to be beside snemulds-shim.nds.
; Relative paths are resolved from THIS folder, not from the selected ROM.
; You may use direct paths, such as /emulators/SNEmulDS.nds instead.

[snemulds]
ntr_path = SNEmulDS.nds
twl_path = SNEmulDS.srl
legacy_path = SNEmulDS_0.6a.nds

; Autoboot options. Holding SELECT bypasses autoboot.
autoboot = false
default = auto
